# config.jp.yml — 日本株・個別株・20万円・1株取引 前提（東京エレクトロン除外）
universe:
  - 8306.T   # 三菱UFJ
  - 8316.T   # 三井住友FG
  - 8411.T   # みずほ
  - 8058.T   # 三菱商事
  - 8031.T   # 三井物産
  - 8053.T   # 住友商事
  - 7203.T   # トヨタ
  - 7267.T   # ホンダ
  - 7201.T   # 日産
  - 7261.T   # マツダ
  - 6758.T   # ソニーG
  - 6501.T   # 日立
  - 6857.T   # アドバンテスト
  - 6920.T   # レーザーテック
  - 6981.T   # 村田製作所
  - 6762.T   # TDK
  - 7735.T   # SCREEN
  - 9432.T   # NTT
  - 9433.T   # KDDI
  - 9434.T   # ソフトバンク
  - 9984.T   # ソフトバンクG
  - 3382.T   # セブン&アイ
  - 9843.T   # ニトリHD
  - 8267.T   # イオン
  - 6301.T   # コマツ
  - 6367.T   # ダイキン
  - 6594.T   # 日本電産
  - 4063.T   # 信越化学
  - 5401.T   # 日本製鉄
  - 6902.T   # デンソー
  - 6098.T   # リクルート
  - 2914.T   # JT
  - 8001.T   # 伊藤忠
  - 8002.T   # 丸紅
  - 2768.T   # 双日
  - 6503.T   # 三菱電機
  - 6954.T   # ファナック
  - 6988.T   # 日東電工
  - 5108.T   # ブリヂストン
  - 4502.T   # 武田薬品
  - 7269.T   # スズキ
  - 7974.T   # 任天堂
  - 4755.T   # 楽天G
  - 2413.T   # エムスリー
  - 7731.T   # ニコン
  - 7733.T   # オリンパス
  - 7741.T   # HOYA
  - 4661.T   # オリエンタルランド
  - 9020.T   # JR東日本
  - 9022.T   # JR東海
  - 9101.T   # 日本郵船
  - 9104.T   # 商船三井
  - 9107.T   # 川崎汽船
  - 4183.T   # 三井化学
  - 5201.T   # AGC
  - 7751.T   # キヤノン
  - 7202.T   # いすゞ自動車
  - 4503.T   # アステラス製薬
  - 4507.T   # 塩野義製薬

benchmark: 1306.T

# リスクオン時のみ個別株から採用、オフは休む（defensiveは空）
risk_on_assets:
  - 8306.T
  - 8316.T
  - 8411.T
  - 8058.T
  - 8031.T
  - 8053.T
  - 7203.T
  - 7267.T
  - 7201.T
  - 7261.T
  - 6758.T
  - 6501.T
  - 6857.T
  - 6920.T
  - 6981.T
  - 6762.T
  - 7735.T
  - 9432.T
  - 9433.T
  - 9434.T
  - 9984.T
  - 3382.T
  - 9843.T
  - 8267.T
  - 6301.T
  - 6367.T
  - 6594.T
  - 4063.T
  - 5401.T   # 日本製鉄
  - 6902.T   # デンソー
  - 6098.T   # リクルート
  - 2914.T   # JT
  - 8001.T   # 伊藤忠
  - 8002.T   # 丸紅
  - 2768.T   # 双日
  - 6503.T   # 三菱電機
  - 6954.T   # ファナック
  - 6988.T   # 日東電工
  - 5108.T   # ブリヂストン
  - 4502.T   # 武田薬品
  - 7269.T   # スズキ
  - 7974.T   # 任天堂
  - 4755.T   # 楽天G
  - 2413.T   # エムスリー
  - 7731.T   # ニコン
  - 7733.T   # オリンパス
  - 7741.T   # HOYA
  - 4661.T   # オリエンタルランド
  - 9020.T   # JR東日本
  - 9022.T   # JR東海
  - 9101.T   # 日本郵船
  - 9104.T   # 商船三井
  - 9107.T   # 川崎汽船
  - 4183.T   # 三井化学
  - 5201.T   # AGC
  - 7751.T   # キヤノン
  - 7202.T   # いすゞ自動車
  - 4503.T   # アステラス製薬
  - 4507.T   # 塩野義製薬
defensive_assets: []   # 原則「休む」

data_days: 420
regime_ma: 100
atr_period: 14
atr_mult_stop: 2.0
top_k: 1
capital: 200000
risk_per_trade: 0.005  # 0.5% = 1,000円
min_turnover_jpy: 100000000  # 20日平均売買代金 1億円未満は除外（目安）
hold_days: 1
outdir: reports

# 1株取引前提（単元未満株）: 1。100株単元のみなら 100 に変更
lot_size_default: 1
lot_size_map: {}

# イベント除外リスト（任意）: CSV で "ticker,until,reason"（untilはYYYY-MM-DD）
events_csv: config/events_ignore.csv

# メール送信（任意）: Gmailのアプリパスワード推奨（環境変数 EMAIL_USER / EMAIL_PASS を使用）
email_enabled: false
email_to: "you@example.com"
email_subject: "DAILY-JP PLAN"

# スコアの重み（必要なら調整）
w_trend: 0.30
w_momo: 0.25
w_volume: 0.20
w_breakout: 0.15
w_structure: 0.10

# 追加オプション（拡張）
# 手数料/スリッページ（仮定値）
commission_per_trade_jpy: 0.0
slippage_bps: 0.0

# 分散制約・相関
sector_map_csv: config/sector_map.csv
sector_max_fraction: 1.0   # 例: 0.5 で採用中の50%まで
corr_max: 1.0              # 例: 0.8 以上の高相関は回避
corr_lookback_days: 20

# ポートフォリオ配分（有効化する場合）
risk_total_pct: 0.0        # 例: 0.01 = 資金の1%（0は無効）
risk_allocation_mode: per_trade  # or "portfolio"

# リスクオフ時も採用する場合（防御モード）
allow_pick_in_risk_off: false
risk_off_risk_scale: 0.5

# 追加スコア重み
w_strength: 0.05
